### ISSUE TITLE
Having trouble using external fonts & `display:block`.

### ISSUE THREAD

**Issue by jessekahner** [kvnang/workers-og#1]
Thanks for this project!
I'm exploring this worker as a way to some default OG images for our site, I'm able to get the font's `arrayBuffer`, but everytime I try to use it in the `ImageResponse`, I get in the console:
```
A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #2)
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '263')
Uncaught (in response) TypeError: Cannot read properties of undefined (reading '263')
```
and the page turns blank.

Now if I try to use a `display:block` in my template (I'm trying to use `lineClamp`), I also get a blank screen with this in the console
```
A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #2)
Uncaught (in promise) Error: Invalid value for CSS property "display". Allowed values: "flex" | "none". Received: "block".
Uncaught (in response) Error: Invalid value for CSS property "display". Allowed values: "flex" | "none". Received: "block".
```

Is there anything else I could try, or have you run into this problem?
Thanks and have a good day

**Comment by kvnang** [comment]
Hey thanks for checking out. Could you please explain what the issue is with the fonts, with some reproduction code?

As for `display` issue, that's expected. It only supports `display:flex` given the limitation of the underlying layout engine, Yoga layout.

**Comment by jessekahner** [comment]
Thanks for your quick response!

Now for the font issue, I'm afraid that was on my end. I was `OTF` files that had "something" in them. Once I tried with a `TTF`, all was good!

Now for the `display` issue... I get that, but I'm trying to see how to replicate the example here:
https://og-playground.vercel.app/?share=5VPBbtQwEP2VkRFakNKSshxQBBwoXDhwaEFc9uLYk6xbx2PZk-6G1Up8DR_GlzDOkgr13FtPGb_xvPf8ojkoQxZVo95Zd7cJAJknj-8Ph1IDbNH1W25gdVHXz1fVCdw5y9sHmHU5ej0J2nncL2ipP7mEhh0F6Rny4xCWbtTWutA3cFH_Q1ptbvtEY7CX5CnJxLOu6-7ZKPC1-4kNrF_P0PG4CR9KsZh_aP9_X60nc7tQAXgX8NLrIQrbPTjo1LvwkZhpkJF1HferU69IAcxiAN8zWmgnyDQgUAe8RdhR8naVwQsFZgZDQ9TBYa7gK-75_CYDBt16zDDRCExgEmpG6EbvzzLLy-EHtqBj9M7oElguGjKLocQ0q3iZEPIr1Iahk_kxFQUdLLjA2CcZlKuRdpiEGK7GzGetLn6_6Dt9bZKLLOIkz-8l0DSzdjrPtO3ovM3nc6KvJNJHyHa1ho368-s3vDBihQb5fVayEa-BX27UE093-apKUZxNqeag5v1Szdu6rtRpAVXzphwstmOvmk77jJXCgW7ctymW7eXdfBKesiSfhxatajiNeKwU61ZubNF7mmNUx78

I'm trying to do a `lineClamp`, but the only way it seems to be possible (per their example) is by putting a `display:block` where the line-clamp should be. This issue is less of a blocker for me. It's a very "nice to have". How would you go about and do it?

**Comment by jessekahner** [comment]
I just did and I still wasn't able to use `lineClamp`. No worries, I'll close this issue in the meantime.

Thanks for all your help.

**Comment by kvnang** [comment]
Hey @jessekahner just so you know, I was able to test locally and got it working.

I just updated the packages again as I forgot to update the wasm files.

One thing you'd want to note with `lineClamp` is that the display needs to be `block` and the child of that component must directly be the string (can't be wrapped with another tag). 

I hope this helps!

**Comment by jessekahner** [comment]
It does help & it does work now! Fantastic!

Will close the issue.
