### ISSUE TITLE
Custom fonts?

### ISSUE THREAD

**Issue by ninjamar** [kvnang/workers-og#13]
Is there any support for custom fonts?

**Comment by ninjamar** [comment]
I know I can pass arguments to `ImageResponse`, but `loadGoogleFont` isn't exposed. For me, `loadGoogleFont` has an additional overhead, so I wrote a base64 encoded version of the font to a JavaScript file to be imported.

**Comment by zerosoul** [comment]
> I know I can pass arguments to `ImageResponse`, but `loadGoogleFont` isn't exposed. For me, `loadGoogleFont` has an additional overhead, so I wrote a base64 encoded version of the font to a JavaScript file to be imported.

I want to support Chinese fonts, can you tell me how to do that？

**Comment by ninjamar** [comment]
> > I know I can pass arguments to `ImageResponse`, but `loadGoogleFont` isn't exposed. For me, `loadGoogleFont` has an additional overhead, so I wrote a base64 encoded version of the font to a JavaScript file to be imported.
> 
> I want to support Chinese fonts, can you tell me how to do that？

Here's how I did it
- https://github.com/ninjamar/captcha/blob/main/fonthelper.js
- https://github.com/ninjamar/captcha/blob/main/src/fontdata.js
- https://github.com/ninjamar/captcha/blob/main/src/config.js#L10
- https://github.com/ninjamar/captcha/blob/main/src/index.js#L75
-

**Comment by cmnstmntmn** [comment]
@kvnang hei there, any example of how `loadGoogleFont` can be used?

**Comment by cmnstmntmn** [comment]
oh, found it:

```js
return new ImageResponse(html, {
	width: 1200,
	height: 630,
	fonts: [
	 {
	    name: 'Roboto',
            data: await loadGoogleFont({ family: 'Roboto' }),
	 },
	],
});
```
