### ISSUE TITLE
Enable use of Cloudflare Images

### ISSUE THREAD

**Issue by jessekahner** [kvnang/workers-og#3]
Would it be possible to enable the use of Cloudflare Images to optimize the image generated by the tool?
See here: https://developers.cloudflare.com/images/image-resizing/resize-with-workers/

Or of not CF, then does `vercel` or `satori` have something to enable cleaning up the image?

**Comment by kvnang** [comment]
Yes, you should be able to, but you need to set up the Cloudflare Images integration yourself as it's a separate (paid) product.

There's no built-in feature to optimize the image. Common practice would be to use Node's `sharp` (in which case you need a Node server) or 3rd-party services like Cloudflare Images.
