### ISSUE TITLE
Exception "Promise will never complete." in Pages Function

### ISSUE THREAD

**Issue by NeuronButter** [kvnang/workers-og#5]
Hi there!
I'm trying to use workers-og in a Pages Function, but my Worker keeps throwing `Error: Promise will never complete`. This only occurs when deployed to CF, running this locally in wrangler works fine. I've managed to figure out that the exception occurs when either you try and read the contents (such as `let out = new ImageResponse(...); await out.arrayBuffer()`) or return the new ImageResponse straight back.
Is there any way to fix this? Thanks!

**Comment by kvnang** [comment]
Hey do you have a minimal reproducible code for this issue? I have it running on a Worker and I was able to simply return it `return new ImageResponse( ... )`, so perhaps there are different issues here.

**Comment by NeuronButter** [comment]
Hey there, I've finally worked out why my worker was throwing it. Unrelated, but the same error came up [here](https://community.cloudflare.com/t/tweetnacl-secretbox-on-workers/201649) and made me realise that an image that I was using was unnecessarily large (6000x4000) so it must have gone over a Workers limit once Satori kicked in (don't think it's duration because I thought they did away with that, but maybe memory or CPU time?).
