### ISSUE TITLE
Unnecessary Escaping of '&' Character in sanitizeJSON Function

### ISSUE THREAD

**Issue by kiyopikko** [kvnang/workers-og#6]
Thank you for great project!

I've encountered an issue with the `sanitizeJSON` function, where it unnecessarily escapes the `&` character. This behavior seems to be causing issues when parsing JSON strings.

```js
export const sanitizeJSON = (unsanitized: string) => {
  return unsanitized
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")
    .replace(/\f/g, "\\f")
    .replace(/"/g, '\\"')
    .replace(/\&/g, "\\&"); // this line
};
```

<img width="624" alt="スクリーンショット 2024-01-11 1 53 15" src="https://github.com/kvnang/workers-og/assets/6188979/82c89064-43e8-49c3-99e2-925e837c8999">

If I've misunderstood something, I apologize 🙇

**Comment by kvnang** [comment]
Thanks! You're right, as per [json.org](https://json.org) the ampersand shouldn't be escaped. I've published the new version on NPM based on this commit here:
https://github.com/kvnang/workers-og/commit/9866f9b2c1722252757cb464fa8f133c419b3a56
